### PR TITLE
Trait changes

### PR DESCRIPTION
**Pull request by forus**
Changes to make SmartR works for TraIT version of TranSMART (https://github.com/CTMM-TraIT/transmartApp). These changes would be needed to make SmarR works for the research brunch (https://github.com/transmart/transmartApp/tree/research)

### CODE REVIEW

**Comment by sherzinger** [comment]
I can't accept this PR because the whole front-end changed (which is why no one touched this I assume). I integrated these changes into the new code, except of the removal of SmartRExportedUrlMappings.groovy. 

@cataphract introduced this file. Can we safely remove it?

**Comment by cataphract** [comment]
This needs to be rebased on top of the new version then. `SmartRExportedUrlMappings.groovy` shouldn't be there no.

**Comment by cataphract** [comment]
BTW I didn't introduce the file, I renamed it from `ExportedUrlMappings.groovy` to avoid a conflict with RModules. The thing is this plugin doesn't need to export any URL mappings and the mappings it is exporting conflict with the rules in `transmartApp`.

**Comment by rnugraha** [comment]
Not applicable to current smarR. @forus Pls create new PR if you're using latest smartR

**Pull request closed without merging**
